server:
  port: 8081
  servlet:
    context-path: /v1
security:
  oauth2:
    resource:
      id: spasso
      jwk:
        key-set-uri: http://localhost:8080/auth/realms/spasso/protocol/openid-connect/certs
